---
server:
  host:
  port: 8181

db:
  connstr: 'postgresql://$POSTGRESQL_USER:$POSTGRESQL_PASSWORD@postgresql.turtl.svc:5432/sampledb'
  pool: 24

loglevel: 'debug'

app:
  enable_bookmarker_proxy: false
  api_url: 'http://black-turtl.apps.95.216.40.23.nip.io:8181'
  www_url: 'https://black-turtl.apps.95.216.40.23.nip.io/'
  emails:
    admin: 'admin@turtlapp.com1'
    info: 'Turtl <info@turtlapp.com>'
    invites: 'invites@turtlapp.com'
  secure_hash_salt: "If you create a configmap from a file, you can include files containing non-UTF8 data will be placed in this new field without corrupting the non-UTF8 data. OpenShift Container Platform detects binary files and transparently encodes the file as MIME. On the server, the MIME payload is decoded and stored without corrupting the data."
  allow_unconfirmed_invites: false

sync:
  max_bulk_sync_records: 32

plugins:
  plugin_location: '/var/www/turtl/server/plugins'
  email:
    enabled: false
    endpoint: 'smtps://user:password@smtp.gmail.com/?pool=true'
    defaults: {}

uploads:
  local: '/var/www/turtl/server/public/uploads'
  local_proxy: true
  url: 'http://api.turtl.dev/uploads'

  #s3:
  #  token: 'IHADAPETSNAKEBUTHEDIEDNOOOOO'
  #  secret: ''
  #  bucket: ''
  #  endpoint: 'https://s3.amazonaws.com'

